template_name: "Support Sphere"
template_image: "/image-resize?name=/media/KnowledgeBase.jpg"
description: "A support sphere template visually represents layers of support or assistance, showing how resources or help radiate outward from a central point."
type: "Knowledge base"
channel: "Blog,Knowledge Base"
html_templates: "default.html"

